name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -c "from armodels_bot import ModelsTelegramBot; print('✅ Импорт прошел успешно')"

      - name: Check code style
        run: |
          pip install flake8
          flake8 armodels_bot.py --count --select=E9,F63,F7,F82 --show-source --statistics || true
